// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_schemas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configSchemaExists = `-- name: ConfigSchemaExists :one
SELECT EXISTS(
    SELECT 1 FROM config_schemas WHERE id = $1
) AS exists
`

func (q *Queries) ConfigSchemaExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, configSchemaExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const configSchemaExistsByName = `-- name: ConfigSchemaExistsByName :one
SELECT EXISTS(
    SELECT 1 FROM config_schemas WHERE name = $1
) AS exists
`

func (q *Queries) ConfigSchemaExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, configSchemaExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countConfigSchemas = `-- name: CountConfigSchemas :one
SELECT COUNT(*) FROM config_schemas
`

func (q *Queries) CountConfigSchemas(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfigSchemas)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfigsUsingSchema = `-- name: CountConfigsUsingSchema :one
SELECT COUNT(*) FROM configs
WHERE schema_id = $1
`

func (q *Queries) CountConfigsUsingSchema(ctx context.Context, schemaID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConfigsUsingSchema, schemaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfigSchema = `-- name: CreateConfigSchema :one
INSERT INTO config_schemas (
    id,
    name,
    schema_content,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, schema_content, created_by_user_id, created_at, updated_at
`

type CreateConfigSchemaParams struct {
	ID              string `db:"id" json:"id"`
	Name            string `db:"name" json:"name"`
	SchemaContent   string `db:"schema_content" json:"schema_content"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) CreateConfigSchema(ctx context.Context, arg CreateConfigSchemaParams) (ConfigSchema, error) {
	row := q.db.QueryRow(ctx, createConfigSchema,
		arg.ID,
		arg.Name,
		arg.SchemaContent,
		arg.CreatedByUserID,
	)
	var i ConfigSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaContent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfigSchema = `-- name: DeleteConfigSchema :exec
DELETE FROM config_schemas
WHERE id = $1
`

func (q *Queries) DeleteConfigSchema(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteConfigSchema, id)
	return err
}

const getConfigSchemaByID = `-- name: GetConfigSchemaByID :one
SELECT id, name, schema_content, created_by_user_id, created_at, updated_at FROM config_schemas
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConfigSchemaByID(ctx context.Context, id string) (ConfigSchema, error) {
	row := q.db.QueryRow(ctx, getConfigSchemaByID, id)
	var i ConfigSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaContent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigSchemaByName = `-- name: GetConfigSchemaByName :one
SELECT id, name, schema_content, created_by_user_id, created_at, updated_at FROM config_schemas
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetConfigSchemaByName(ctx context.Context, name string) (ConfigSchema, error) {
	row := q.db.QueryRow(ctx, getConfigSchemaByName, name)
	var i ConfigSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaContent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigSchemas = `-- name: ListConfigSchemas :many
SELECT id, name, schema_content, created_by_user_id, created_at, updated_at FROM config_schemas
ORDER BY name
`

func (q *Queries) ListConfigSchemas(ctx context.Context) ([]ConfigSchema, error) {
	rows, err := q.db.Query(ctx, listConfigSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigSchema{}
	for rows.Next() {
		var i ConfigSchema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaContent,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigSchemasByCreator = `-- name: ListConfigSchemasByCreator :many
SELECT id, name, schema_content, created_by_user_id, created_at, updated_at FROM config_schemas
WHERE created_by_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConfigSchemasByCreator(ctx context.Context, createdByUserID string) ([]ConfigSchema, error) {
	rows, err := q.db.Query(ctx, listConfigSchemasByCreator, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigSchema{}
	for rows.Next() {
		var i ConfigSchema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaContent,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfigSchema = `-- name: UpdateConfigSchema :one
UPDATE config_schemas
SET
    name = COALESCE($2, name),
    schema_content = COALESCE($3, schema_content),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, schema_content, created_by_user_id, created_at, updated_at
`

func (q *Queries) UpdateConfigSchema(ctx context.Context, iD string, name pgtype.Text, schemaContent pgtype.Text) (ConfigSchema, error) {
	row := q.db.QueryRow(ctx, updateConfigSchema, iD, name, schemaContent)
	var i ConfigSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaContent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
