// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RoleLevel string

const (
	RoleLevelAdmin  RoleLevel = "admin"
	RoleLevelEditor RoleLevel = "editor"
	RoleLevelViewer RoleLevel = "viewer"
)

func (e *RoleLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleLevel(s)
	case string:
		*e = RoleLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleLevel: %T", src)
	}
	return nil
}

type NullRoleLevel struct {
	RoleLevel RoleLevel `json:"role_level"`
	Valid     bool      `json:"valid"` // Valid is true if RoleLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RoleLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleLevel), nil
}

func (e RoleLevel) Valid() bool {
	switch e {
	case RoleLevelAdmin,
		RoleLevelEditor,
		RoleLevelViewer:
		return true
	}
	return false
}

func AllRoleLevelValues() []RoleLevel {
	return []RoleLevel{
		RoleLevelAdmin,
		RoleLevelEditor,
		RoleLevelViewer,
	}
}

// Current authoritative configuration state (requires Raft consensus)
type Config struct {
	// Reference to project (part of composite PK)
	ProjectID string `db:"project_id" json:"project_id"`
	// Configuration key (part of composite PK)
	Key string `db:"key" json:"key"`
	// Reference to validation schema
	SchemaID string `db:"schema_id" json:"schema_id"`
	// Optimistic locking version counter
	Version int64 `db:"version" json:"version"`
	// Canonical configuration data (JSON)
	Content []byte `db:"content" json:"content"`
	// User who last updated this config
	UpdatedByUserID string           `db:"updated_by_user_id" json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Immutable audit log of all configuration changes
type ConfigRevision struct {
	// Unique revision identifier (UUID)
	ID string `db:"id" json:"id"`
	// Reference to project
	ProjectID string `db:"project_id" json:"project_id"`
	// Configuration key
	ConfigKey string `db:"config_key" json:"config_key"`
	// Version number of this revision
	Version int64 `db:"version" json:"version"`
	// Full historical configuration data (JSON)
	Content []byte `db:"content" json:"content"`
	// User who created this revision
	CreatedByUserID string           `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

// Reusable JSON Schema definitions for configuration validation
type ConfigSchema struct {
	// Unique schema identifier (UUID)
	ID string `db:"id" json:"id"`
	// Schema name for reference
	Name string `db:"name" json:"name"`
	// JSON Schema definition
	SchemaContent string `db:"schema_content" json:"schema_content"`
	// User who created this schema
	CreatedByUserID string           `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Projects for multi-tenancy scoping
type Project struct {
	// Unique project identifier (UUID)
	ID string `db:"id" json:"id"`
	// Project name
	Name string `db:"name" json:"name"`
	// API key for client access (unique)
	ApiKey string `db:"api_key" json:"api_key"`
	// Reference to the project owner
	OwnerUserID string           `db:"owner_user_id" json:"owner_user_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// User roles for access control within projects
type Role struct {
	// Reference to user
	UserID string `db:"user_id" json:"user_id"`
	// Reference to project
	ProjectID string `db:"project_id" json:"project_id"`
	// Role level: admin, editor, or viewer
	RoleLevel RoleLevel        `db:"role_level" json:"role_level"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Users with access to the management UI
type User struct {
	// Unique user identifier (UUID)
	ID string `db:"id" json:"id"`
	// User email address (unique)
	Email string `db:"email" json:"email"`
	// Bcrypt hashed password
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
