// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByOwner = `-- name: CountProjectsByOwner :one
SELECT COUNT(*) FROM projects
WHERE owner_user_id = $1
`

func (q *Queries) CountProjectsByOwner(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOwner, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    name,
    api_key,
    owner_user_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, api_key, owner_user_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	ApiKey      string `db:"api_key" json:"api_key"`
	OwnerUserID string `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.ApiKey,
		arg.OwnerUserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByAPIKey = `-- name: GetProjectByAPIKey :one
SELECT id, name, api_key, owner_user_id, created_at, updated_at FROM projects
WHERE api_key = $1
LIMIT 1
`

func (q *Queries) GetProjectByAPIKey(ctx context.Context, apiKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByAPIKey, apiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, api_key, owner_user_id, created_at, updated_at FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, api_key, owner_user_id, created_at, updated_at FROM projects
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKey,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, name, api_key, owner_user_id, created_at, updated_at FROM projects
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerUserID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKey,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE id = $1
) AS exists
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectExistsByAPIKey = `-- name: ProjectExistsByAPIKey :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE api_key = $1
) AS exists
`

func (q *Queries) ProjectExistsByAPIKey(ctx context.Context, apiKey string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExistsByAPIKey, apiKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectExistsByName = `-- name: ProjectExistsByName :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE name = $1
) AS exists
`

func (q *Queries) ProjectExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE($2, name),
    api_key = COALESCE($3, api_key),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, api_key, owner_user_id, created_at, updated_at
`

func (q *Queries) UpdateProject(ctx context.Context, iD string, name pgtype.Text, apiKey pgtype.Text) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, iD, name, apiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
