// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRole(ctx context.Context, userID string, projectID string, roleLevel RoleLevel) (Role, error)
	ChangeConfigSchema(ctx context.Context, arg ChangeConfigSchemaParams) (Config, error)
	ConfigExists(ctx context.Context, projectID string, key string) (bool, error)
	ConfigSchemaExists(ctx context.Context, id string) (bool, error)
	ConfigSchemaExistsByName(ctx context.Context, name string) (bool, error)
	CountConfigSchemas(ctx context.Context) (int64, error)
	CountConfigsByProject(ctx context.Context, projectID string) (int64, error)
	CountConfigsBySchema(ctx context.Context, schemaID string) (int64, error)
	CountConfigsUsingSchema(ctx context.Context, schemaID string) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountProjectsByOwner(ctx context.Context, ownerUserID string) (int64, error)
	CountRevisions(ctx context.Context, projectID string, configKey string) (int64, error)
	CountRevisionsByProject(ctx context.Context, projectID string) (int64, error)
	CountRolesByProject(ctx context.Context, projectID string) (int64, error)
	CountRolesByUser(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error)
	CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) (ConfigRevision, error)
	CreateConfigSchema(ctx context.Context, arg CreateConfigSchemaParams) (ConfigSchema, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, iD string, email string, passwordHash string) (User, error)
	DeleteConfig(ctx context.Context, projectID string, key string) error
	DeleteConfigSchema(ctx context.Context, id string) error
	DeleteOldRevisions(ctx context.Context, projectID string, configKey string, version int64) error
	DeleteProject(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetConfig(ctx context.Context, projectID string, key string) (Config, error)
	GetConfigRevision(ctx context.Context, id string) (ConfigRevision, error)
	GetConfigRevisionByVersion(ctx context.Context, projectID string, configKey string, version int64) (ConfigRevision, error)
	GetConfigSchemaByID(ctx context.Context, id string) (ConfigSchema, error)
	GetConfigSchemaByName(ctx context.Context, name string) (ConfigSchema, error)
	GetConfigVersion(ctx context.Context, projectID string, key string) (int64, error)
	GetConfigWithVersion(ctx context.Context, projectID string, key string, version int64) (Config, error)
	GetConfigsUpdatedAfter(ctx context.Context, projectID string, updatedAt pgtype.Timestamp) ([]Config, error)
	GetConfigsUpdatedByUser(ctx context.Context, updatedByUserID string, limit int32) ([]Config, error)
	GetLatestNRevisions(ctx context.Context, projectID string, configKey string, limit int32) ([]ConfigRevision, error)
	GetLatestRevision(ctx context.Context, projectID string, configKey string) (ConfigRevision, error)
	GetProjectByAPIKey(ctx context.Context, apiKey string) (Project, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetRevisionHistory(ctx context.Context, projectID string, configKey string, limit int32) ([]GetRevisionHistoryRow, error)
	GetRevisionsCreatedAfter(ctx context.Context, projectID string, configKey string, createdAt pgtype.Timestamp) ([]ConfigRevision, error)
	GetRevisionsInVersionRange(ctx context.Context, arg GetRevisionsInVersionRangeParams) ([]ConfigRevision, error)
	GetRole(ctx context.Context, userID string, projectID string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserRole(ctx context.Context, userID string, projectID string) (RoleLevel, error)
	ListAllRevisionsByProject(ctx context.Context, projectID string) ([]ConfigRevision, error)
	ListConfigRevisions(ctx context.Context, projectID string, configKey string) ([]ConfigRevision, error)
	ListConfigRevisionsPaginated(ctx context.Context, arg ListConfigRevisionsPaginatedParams) ([]ConfigRevision, error)
	ListConfigSchemas(ctx context.Context) ([]ConfigSchema, error)
	ListConfigSchemasByCreator(ctx context.Context, createdByUserID string) ([]ConfigSchema, error)
	ListConfigsByProject(ctx context.Context, projectID string) ([]Config, error)
	ListConfigsBySchema(ctx context.Context, schemaID string) ([]Config, error)
	ListProjectRoles(ctx context.Context, projectID string) ([]ListProjectRolesRow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByOwner(ctx context.Context, ownerUserID string) ([]Project, error)
	ListRevisionsByUser(ctx context.Context, createdByUserID string, limit int32) ([]ConfigRevision, error)
	ListRolesByLevel(ctx context.Context, roleLevel RoleLevel) ([]ListRolesByLevelRow, error)
	ListUserRoles(ctx context.Context, userID string) ([]ListUserRolesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Optimistic locking helper - get current version for update
	LockConfigForUpdate(ctx context.Context, projectID string, key string) (int64, error)
	ProjectExists(ctx context.Context, id string) (bool, error)
	ProjectExistsByAPIKey(ctx context.Context, apiKey string) (bool, error)
	ProjectExistsByName(ctx context.Context, name string) (bool, error)
	RevokeAllProjectRoles(ctx context.Context, projectID string) error
	RevokeAllUserRoles(ctx context.Context, userID string) error
	RevokeRole(ctx context.Context, userID string, projectID string) error
	RoleExists(ctx context.Context, userID string, projectID string) (bool, error)
	SearchConfigsByKey(ctx context.Context, projectID string, key string, limit int32) ([]Config, error)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) (Config, error)
	UpdateConfigSchema(ctx context.Context, iD string, name pgtype.Text, schemaContent pgtype.Text) (ConfigSchema, error)
	UpdateProject(ctx context.Context, iD string, name pgtype.Text, apiKey pgtype.Text) (Project, error)
	UpdateRole(ctx context.Context, userID string, projectID string, roleLevel RoleLevel) (Role, error)
	UpdateUser(ctx context.Context, iD string, email pgtype.Text, passwordHash pgtype.Text) (User, error)
	UserExists(ctx context.Context, id string) (bool, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserHasMinimumRole(ctx context.Context, userID string, projectID string, column3 interface{}) (bool, error)
	UserHasRole(ctx context.Context, userID string, projectID string, roleLevel RoleLevel) (bool, error)
}

var _ Querier = (*Queries)(nil)
